In [13]:
import json
import pandas as pd
import numpy as np
import requests
import time

In [14]:
df_init = pd.read_csv("messages.csv")
df_init.head()

,id,timestamp,sender,channel,message
0,MSG-0001,2025-01-15T06:13:30Z,Sarah Mitchell @ Meridian Markets,broker-chat,mkt in USDCAD: 0.7399 / 0.7402
1,MSG-0002,2025-01-15T06:34:35Z,David Laurent @ Crescent Capital,broker-chat,I have GBPUSD 0.8386 / 0.8391 live
2,MSG-0003,2025-01-15T06:37:04Z,Yuki Tanaka @ Pacific Securities,sales-desk,hearing large sovereign buying in EURUSD throu...
3,MSG-0004,2025-01-15T06:51:42Z,Mike (Sales),sales-desk,"saw your email, will respond properly after lunch"
4,MSG-0005,2025-01-15T06:53:35Z,Tom Richards @ Summit Brokerage,broker-chat,USDJPY 140.6/140.61

In [15]:
df_init.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         435 non-null    object
 1   timestamp  435 non-null    object
 2   sender     435 non-null    object
 3   channel    435 non-null    object
 4   message    435 non-null    object
dtypes: object(5)
memory usage: 17.1+ KB

In [17]:
df_test = pd.read_csv("messages_labeled.csv")
df_test.head()

,id,timestamp,sender,channel,message,intent,product,direction,instrument,amount,price
0,MSG-0001,2025-01-15T06:13:30Z,Sarah Mitchell @ Meridian Markets,broker-chat,mkt in USDCAD: 0.7399 / 0.7402,price_quote,FX,two_way,USDCAD,NaN,0.7399/0.7402
1,MSG-0002,2025-01-15T06:34:35Z,David Laurent @ Crescent Capital,broker-chat,I have GBPUSD 0.8386 / 0.8391 live,price_quote,FX,two_way,GBPUSD,NaN,0.8386/0.8391
2,MSG-0003,2025-01-15T06:37:04Z,Yuki Tanaka @ Pacific Securities,sales-desk,hearing large sovereign buying in EURUSD throu...,market_commentary,NaN,NaN,NaN,NaN,NaN
3,MSG-0004,2025-01-15T06:51:42Z,Mike (Sales),sales-desk,"saw your email, will respond properly after lunch",noise,NaN,NaN,NaN,NaN,NaN
4,MSG-0005,2025-01-15T06:53:35Z,Tom Richards @ Summit Brokerage,broker-chat,USDJPY 140.6/140.61,price_quote,FX,two_way,USDJPY,NaN,140.6/140.61

In [21]:
for intent in df_test["intent"].unique():
    count = df_test[df_test["intent"] == intent].shape[0]
    print(f"{intent}: {count} messages")

price_quote: 25 messages
market_commentary: 20 messages
noise: 15 messages
rfq: 25 messages
operational: 15 messages

In [20]:
df_test.shape

(100, 11)